export const STATISTIC_USERS = "STATISTIC_USERS";
export const STATISTIC_INCOME_AMOUTH = "STATISTIC_INCOME_AMOUTH";
export const STATISTIC_MONTHLY_SALES = "STATISTIC_MONTHLY_SALES";
export const STATISTIC_FOOD_SALES = "STATISTIC_FOOD_SALES";
export const STATISTIC_ORDERS_USER = "STATISTIC_ORDERS_USER";
export const STATISTIC_ORDERS_BY_CATEGORY = "STATISTIC_ORDERS_BY_CATEGORY";


